services:
  
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  discount.api:
    image: discount.api
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
  mssql_data:
